name=PButton
version=0.0.1
author=Lautaro Ezequiel Rodriguez Base lerb.dev@gmail.com
maintainer=Lautaro Ezequiel Rodriguez Base lerb.dev@gmail.com
sentence=Library for reading digital inputs.
paragraph=This library allows reading multiple digital inputs without delay and without bouncing, to execute different functions with each of the inputs.
category=Signal Input/Output
url=https://github.com/LautaroRodriguezBase/PButton
architectures=*
